language: php

compiler:
  - gcc
  - clang

sudo: required

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - g++ -o libjieba.so -fPIC -c -DLOGGING_LEVEL=LL_WARNING -I./include/ lib/jieba.cpp
  - phpize
  - ./configure
  - make
  - make install

before_script:
  - cd $TRAVIS_BUILD_DIR/tests
  - composer update -o

script:
  - cd $TRAVIS_BUILD_DIR/tests
  - pwd
  - ls -al
  - ls -al vendor/bin
  - composer test
