language: php

compiler:
  - gcc
  - clang

sudo: required

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - g++ -o libjieba.so -fPIC -c -DLOGGING_LEVEL=LL_WARNING -I./include/ lib/jieba.cpp
  - phpize
  - ./configure
  - make

before_script:
  - cd $TRAVIS_BUILD_DIR/tests
  - composer update

script:
  - cd $TRAVIS_BUILD_DIR/tests
  - pwd
  - ls -al
  - vendor/bin/phpunit test
