# syntax version.
version: "3.7"

volumes:
  php-alpine-cache-v3.9:
  php-alpine-cache-v3.10:
  php-alpine-cache-v3.11:
  php-alpine-cache-v3.12:
  php-alpine-cache-v3.13:
  php-alpine-cache-v3.14:

# services list.
services:
  # base image
  jieba-ext:
    image: "hyperf/jieba:${PHP_VERSION}-v${ALPINE_VERSION}"
    build:
      context: "./"
      args:
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
    volumes:
      - "php-alpine-cache-v${ALPINE_VERSION}:/var/cache/apk"
