on: ['push', 'pull_request']

name: Build Asset

jobs:
  build:
    name: Build Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: ./build.sh
