on: ['push', 'pull_request']

name: Build Asset

jobs:
  build:
    name: Build Asset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.3', '7.4', '8.0' ]
        alpine-version: [ '3.10', '3.11', '3.12' ]
        exclude:
          - php-version: '7.3'
            alpine-version: '3.12'
          - php-version: '8.0'
            alpine-version: '3.10'
      max-parallel: 8
      fail-fast: false
    env:
      PHP_VERSION: ${{ matrix.php-version }}
      ALPINE_VERSION: ${{ matrix.alpine-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: ./build.sh
