on: ['push', 'pull_request']

name: Test for Jieba
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.3', '7.4', '8.0' ]
        alpine-version: [ '3.10', '3.11', '3.12' ]
        exclude:
          - php-version: '7.3'
            alpine-version: '3.12'
          - php-version: '8.0'
            alpine-version: '3.10'
      max-parallel: 8
      fail-fast: false
    env:
      PHP_VERSION: ${{ matrix.php-version }}
      ALPINE_VERSION: ${{ matrix.alpine-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
      - name: Setup Jieba
        run: |
          g++ -o libjieba.so -fPIC -c -DLOGGING_LEVEL=LL_WARNING -I./include/ lib/jieba.cpp
          phpize
          ./configure
          make
          sudo make install
      - name: Test
        run: php -d extension=jieba.so examples/test.php
